### ISSUE TITLE
`/hubsupport` search fails when the search term contains a space

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite-discord-bot#110]
Searching `plank` correctly finds [the Plank Sack hub plugin](https://runelite.net/plugin-hub/show/plank-sack), however searching `plank s` (or any other substring) comes back with no results.

**Comment by JamesJJT** [comment]
@Nightfirecat Do you still want someone to look at this issue?

If so, i can probably take a look, in the later part of this week.
