### ISSUE TITLE
unable to reverify discord account after rejoining discord server

### ISSUE THREAD

**Issue by joey-colon** [runelite/runelite-discord-bot#47]
I am trying to reverify my Discord account with my Github account in order to gain access to chat in the #development channel on Discord. When I go to paste my token into the bot via `!ghauth xxx`, it says `Your GitHub account is already linked to this Discord user`, but I don't have the role on my Discord account. 

Also, when I send `!ghwhois joey#1337` it is stating that there is no github account linked to the Discord account.

**Comment by Nightfirecat** [comment]
The bot currently has `@223169696055296011` registered to your github account, who it reports as having the nick/number `joey#1337`. Is that not you?

**Comment by joey-colon** [comment]
> The bot currently has `@223169696055296011` registered to your github account, who it reports as having the nick/number `joey#1337`. Is that not you?

yes that's me, but i no longer have the role needed to talk in the development channel because i left the server

**Comment by deathbeam** [comment]
Yea so the issue is that the bot do not checks if you have role, only if you did registered. And you did. This should be easy fix, i will look at it later
